# Generated by Django 4.2.11 on 2024-03-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
